[default.extend-identifiers]
WlQ2PN0Fmhg = "WlQ2PN0Fmhg"

[default.extend-words]
# Don't correct these word (parts)
softwares = "softwares"

[files]
# Files containing french words
extend-exclude = [
    "content/news/2023-11-19-CExA-coffees/index.md",
    "content/news/2023-11-20-PTC/index.md",
    "content/news/2023-11-27-First-CExA-coffee/index.md",
    "content/news/2024-01-15-Third-CExA-coffee/index.md"
]
