---
name: Website tests

on:
  schedule:
    - cron: "0 1 * * 0"  # At 01:00 on Sunday.
  workflow_dispatch:

jobs:
  trailing-whitespaces-check:
    name: Trailing whitespaces check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Analysing the trailing whitespaces
        run: ./bin/trailing_spaces --Werror $(git ls-files 'content/*.md')

  links-check:
    name: Links check using linkchecker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install linkchecker
        run: |
          pipx install linkchecker
      - name: Analysing the links of the website
        run: |
          linkchecker --config=.linkcheckerrc --threads=4 --check-extern https://cexa-project.org
